excluded_dates: 
    - "2020-11-26"
    
index_features:
    - "id"
    - "timestamp"
    
utility_features:
    - "util_feature"
    
categoric_features:
    - "categoric_feature"
    
nlp_features:
    - "text_feature_1"
    - "text_feature_2"

numeric_features:
    - "numeric_feature_1"
    - "numeric_feature_2"

smalls: 0.01
date_feature: "timestamp_date"
target_feature: "target_feature"
nltk_data_dir: "/nltk_data" # change this