db_args:
    host: ""
    user: ""
    password: ""
    port: 0000
    db: "" 

trained_on_date_col_name: "model_trained_on"
expires_on_date_col_name: "model_expires_on"
train_interval: 7
model_info_db_name: "" # change this
model_info_table_name: "" # change this
get_model_info_query: |
    select * 
    from {model_info_db_name}.`{model_info_table_name}`
    order by {trained_on_date_col_name} desc
    limit 1;
    
insert_model_info_query: |
    insert into 
    {model_info_db_name}.`{model_info_table_name}`
    values (
    "{model_trained_on}",
    "{model_expires_on}",
    "{model_output_base_dir}",
    "{train_date_start}",
    "{train_date_end}",
    "{validation_date_start}",
    "{validation_date_end}",
    "{prediction_date_start}",
    "{prediction_date_end}",
    {train_rmse},
    {validation_rmse}
    )