# What amount of lag from today to start predictions data
prediction_end_lag: 4 
# How many days to predict for
n_prediction_days: 1

# How many days before start of prediction data to end the validation set
validation_end_lag: 30
# How many days to use in model validation
n_validation_days: 15

# How many days before start of validation set to end the test set
train_end_lag: 1
# How many days of training data to use
n_train_days: 60

# If you ever need to force a new model to be trained, set this flag to true to for re-training
force_train: False

# How many days before trainng a new model
model_train_interval: 7

output_table_name: '' #change this
outout_db_name: '' # change this
output_query: |
    insert into {outout_db_name}.`{output_table_name}`
    values (
        '{timestamp}', {id}, {prediction}
    )